global:
  scrape_interval: 15s

scrape_configs:
  # FastAPI
  - job_name: "backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:8000"]
  # PostgreSQL
  - job_name: "db"
    static_configs:
      - targets: ["db-exporter:9187"]

