ARG PYTHON_VERSION=3.11-slim


###
FROM python:${PYTHON_VERSION} AS base

LABEL maintainer="vlad-yarko"
LABEL org.opencontainers.image.source="https://github.com/vlad-yarko/my-logging-monitoring"
LABEL org.opencontainers.image.description=Logging/Monitoring

RUN useradd -m locust

# Install curl, because slim does not have it
RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates

RUN curl -sSL https://install.python-poetry.org | python3 -

ENV PATH="/root/.local/bin:$PATH"
# ENV POETRY_VIRTUALENVS_IN_PROJECT=true
ENV POETRY_VIRTUALENVS_IN_PROJECT=false

WORKDIR /app

COPY --chown=locust pyproject.toml poetry.lock* ./


# ###
# FROM base AS dev

RUN poetry install --no-root

COPY --chown=poetry . .

RUN poetry env activate

# RUN poetry run python engine.py

EXPOSE 8089

# USER backend

ENTRYPOINT [ "poetry", "run", "locust", "-f", "locustfile.py" ]
CMD [ "--host", "http://backend:8000", "-u", "4000", "-r", "40", "--loglevel", "INFO", "--autostart" ]
